---
title: "One-number Story"
subtitle: "Mini-project"
format: 
  html:
    toc: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
editor: source
---

::: callout-note
You should be using Word and Excel to complete this activity to gain experience working with Microsoft tools. However, please convert your final submission to a pdf document for ease of providing feedback.

Visit [Cal Poly's Software Hub](https://software.calpoly.edu/) if you do not have Word/Excel. You can either install or run via Office.com. Visit [here](https://tech.calpoly.edu/services/software-downloads) for more detailed instructions about installing software through Cal Poly's AppsAnywhere Client.
:::

## Important Dates

+-------------------------------+------------------------------------------------------------------------------+
| Deliverable                   | Due Date                                                                     |
+===============================+==============================================================================+
| First Draft for Peer Review   | Bring to class on Monday, 4/22                                               |
+-------------------------------+------------------------------------------------------------------------------+
| Peer Review                   | During class Monday, 4/22                                                    |
+-------------------------------+------------------------------------------------------------------------------+
| Final Submission              | Thursday, 4/25 at 11:59pm                                                    |
+-------------------------------+------------------------------------------------------------------------------+
| Live Revisions                | Tuesday, 5/7 -- [sign up](https://calendly.com/calpoly-emily-robinson/15min) |
+-------------------------------+------------------------------------------------------------------------------+

## Instructions

This is a short writing assignment (250-500 words) that focuses on one number (e.g., a maximum, a mean, a percent change, a count, a difference in means, etc.). You may have more number in the story, because you will want to contextualize your number ("as compared to what"), the the focus should be on one small conclusion, one number. Make sure to include a meaningful title/headline in addition to paragraphs to tell your written story.

This number should be calculated from your group project report data. Treat this assignment as an opportunity to consider one story you might tell from the project data.

Use some spreadsheet operations, like [sorting and filtering and pivot tables](https://www.youtube.com/watch?v=kYcpJYmOyCs&list=PLik6fAQnSI92b9mVU-8wMQfuzQa8I7PmS&index=5&ab_channel=AmeliaMcNamara) to narrow your focus to one main value.

::: callout-warning
You are **not** conducting a formal statistical analysis, but instead providing summary statistics to tell your story.
:::

You should keep track of the operations you have done. If you are using spreadsheet operations, this may be a separate sheet of your document, in a text document, etc.

Tracking your operations is important for your work so you can back up your statements with evidence. When you speak to your "editor" (in this class, me or a peer), you may need to justify your claims.

::: callout-tip
### Need inspiration?

While your article should contain the formal journal article elements, read a few short pieces from [Numlock News](https://www.numlock.com/archive) for inspiration.

You may find it useful to watch this video on [interviewing your data](https://www.youtube.com/watch?v=k94zs4dT1QI&list=PLik6fAQnSI92b9mVU-8wMQfuzQa8I7PmS&index=6&t=3s&ab_channel=MJ%27sDataAcademy).

Follow the guidelines described in *Numbers in the Newsroom (ch. 1 and 2).*
:::

Try to apply the principles we discussed in class (streamline sentences, word choice, describing findings, and grammar in Chapter 9 in Communicating with Data) and the data journalism principles listed below.

This is an individual assignment and each group member should calculate their own number and write their own story.

**Data Journalism Principles for Writing with Numbers** *adapted from Numbers in the Newsroom by Sarah Cohen*

1.  **Keep the number of digits in a paragraph below 8.**

-   Before: The Office of Redundancy’s budget rose 48 percent in 2013, from \$700.3 million to \$1.03 billion.
-   Revision: Over the past year, the Office of Redundancy’s budget grew by nearly half, to \$1 billion.

2.  **Round - a lot**

-   Only use precision when it matters. For example, never ever round when it comes to death counts; every body matters.

3.  **Think in ratios**

-   We can't think clearly about very big or very small numbers. Make the numbers you deal with understandable by contextualizing them.

-   Example: A widely quoted estimate of fixing the Year 2000 computer bug was \$50 billion for U.S. companies. How big is \$50 billion? At the time, it was smaller than Bill Gates’ net worth. It was the cost of two hurricanes. It was the income of people living in the Portland, Ore., area.

4.  **Use devices from everyday life**

-   Most people have some arithmetic that they perform instinctively (e.g. discounts in retail, tipping at a restaurant, 2 to 1 odds). Convert your writing into the commonly used scales. Keep in mind that a percent change (implies multiplicative change) is very different from a percentage point difference (implies additive change). Both are correct:
    -   Population growth has slowed by about 1.3 percentage points since its peak in 1950, to 0.7 percent. (Simple difference between 2 percent and 0.7 percent, expressed in percentage points.)
    -   Population growth in the U.S. slowed by almost two-thirds from its peak in 1950, to 0.7 percent in 2013. (Percent difference between 2 percent and 0.7 percent)

<!-- ## Peer editing -->

<!-- Please bring a **printed** complete draft of your story to class on Monday, 4/22. Please let me know if it is a financial burden for you to print and I can print yours for you.  -->

<!-- You will be assigned a partner to peer-review. You will end up reading the piece you are editing multiple times, in order to check all of the important components. I will bring printed copies of the following guide to class (this is not graded and you do not need to turn it in to me, although you will recieve credit for participating that day): -->

<!-- + Reviewer (this is your name and potentially contact information): -->

<!-- + Whose work you are reviewing (their name(s) go here): -->

<!-- *NOTE: For each of these questions, please respond legibly, clearly, and politely. One of the goals of this assignment is to help maximize everyone's performance, so try to be helpful and focused on things that are good already and how to elevate any parts of the report that are not quite there yet!* -->

<!-- As you read: -->

<!-- 1. What is one thing that this story does well that you enjoyed while reading? -->

<!-- 2. What is one question you had while reading? Note that this question might be answered later in the story. Our purpose here is to help individuals identify places where they might want to change the order in which some information is presented. -->

<!-- 3. What is one aspect of the story that felt incomplete? This could be as general or specific as you like and is not necessarily an indication of a group's final grade. -->

<!-- 4. Comment on the story's use of summary statistics. What is working well here and what isn't? -->

<!-- After Reading: -->

<!-- 1. What would be your approximate guess at this story's final score based on the rubric below? It would be helpful to list any areas where you think the score would be quite low. -->

<!-- 2. What is one thing (or more) that you plan to incorporate into your own story now that you've read this one? You might want to take a picture of this answer so that you can remember, as this sheet will go back to the individual who you reviewed. -->

<!-- 3. What is one thing that you hope this individual can refine or improve before they turn in their report? Try to be specific and polite. -->

## Peer Editing

Find someone else in the class that is not in your project group (you can have a group of 3).

Share either a printed or virtual copy of your story with them (give them editing privileges).

#### READ

Read through the entire document first without stopping to comment to get a sense of the story and the goal of the writing.

#### FEEDBACK

Go back to the top of the document and re-read sections as they relate to the content/structure below. Give feedback (see the ACTION comments).

-   **Introduction:** Read just the title/headline and the first sentence. Do they hook you? Do you want to keep reading? Why or why not?

    -   **ACTION:** Add a comment in the document giving constructive feedback on the first sentence and title (e.g. what is working well, what might be changed to improve it).

-   **Background/Context:** Do the introductory paragraphs provide a sense of motivation (why is this important or worth considering)? Do they give a sense of the larger problem that will be addressed?

    -   **ACTION:** Add a comment in the document giving constructive feedback on the background/context (e.g. what is working well, what might be changed to improve it).

-   **Story:** What is the story? Locate it in the rough draft: is it clearly stated? Help the author decide if it is too broad, too narrow, or just right. Work on rewording if necessary.

    -   **ACTION:** Add a comment in the document giving constructive feedback on the story (e.g. what is clear, what might be changed to improve it).

-   **Sentences:** Read the rest of the piece, paying close attention to each sentence and to the flow of one sentence into the next.

    -   Are there mistakes in grammar, usage, spelling, or typing?

        -   **ACTION:** Mark them on the draft with a comment or change to "giving suggestions" mode.

    -   Do the sentences flow nicely, or do some of them feel as if they need reworking?

        -   **ACTION:** Choose two sentences that you feel may need work, highlight them on the rough draft, and add a comment to make suggestions for possible revisions.

-   **Evidence:** Is there adequate evidence in the piece to support the author’s argument?

    -   Are there too many digits?

    -   Does the author leave out any evidence that seems particularly obvious or helpful to you?

    -   Glance through the data operations. Do the numbers and conclusions drawn by the author appear appropriate? Can you spot any obvious mistakes? In particular, pay attention to the “compared to what” problem– is the author comparing apples to apples?

        -   **ACTION:** Add a comment in the document giving constructive feedback on the numerical evidence (e.g. what is working well, what might be changed to improve it).

#### Self Reflection

What is one thing (or more) that you plan to incorporate into your own story now that you've read this one? You might want to take a picture of this answer so that you can remember, as this sheet will go back to the individual who you reviewed.

#### DISCUSS

Once everyone has read through the documents and given written feedback. Discuss as a group.

Focus on lifting up the effective aspects of their writing and sharing ideas of how to make it a more interesting and effective story.

## Final Submission Rubric

To meet the "satisfactory" requirements for the contract, this project must:

-   be turned in on time (or within the agreed upon time by 24-hour "Grace Days")

-   include all components described above

-   Meet quality guidelines laid out in the following rubric (all 2s and above for each element and demonstration of additional considerations)

::: column-page
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------+
| Element             | 3 - strong evidence                                                                                                                           | 2 - moderate evidence                                                                   | 1 - weak evidence                                                                          | 0 - no evidence                                           |
+=====================+===============================================================================================================================================+=========================================================================================+============================================================================================+===========================================================+
| Headline            | The headline is highly relevant, creative, and clear and immediately draws the reader's attention.                                            | The headline is relevant to the topic and is creative and/or clear.                     | The headline is somewhat relevant to the topic but lacks creativity or clarity.            | No headline or headline is not relevant to the topic.     |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------+
| Byline              | The byline identifies the author and establishes strong credibility and professionalism.                                                      | The byline identifies the author and demonstrates some credibility and professionalism. | The byline identifies the author but lacks credibility or professionalism.                 | No byline or author is not identified.                    |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------+
| Lede/Intro          | The intro or lede answers all five Ws: it is highly relevant to the topic, creative, clear, and immediately engages the reader.               | The intro or lede answers some of the five W's and is creative and/or clear.            | The intro or lede partially answers some of the five W's, but lacks creativity or clarity. | No intro or lede, or intro is not relevant to the topic.  |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------+
| Nutgraf/Story       | The nutgraf is highly relevant to the topic, provides clear and sufficient detail, and effectively summarizes the article's main points.      | The nutgraf is relevant to the topic and provides clear and sufficient detail.          | The nutgraf is somewhat relevant to the topic but lacks clarity or detail.                 | No nutgraf or nutgraf is not relevant to the topic.       |
|                     |                                                                                                                                               |                                                                                         |                                                                                            |                                                           |
| ("so what")         |                                                                                                                                               |                                                                                         |                                                                                            |                                                           |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------+
| Exposition/Evidence | The exposition is highly relevant to the topic, provides clear and sufficient detail, and effectively explains the data and its implications. | The exposition is relevant to the topic and provides clear and sufficient detail.       | The exposition is somewhat relevant to the topic but lacks clarity or detail.              | No exposition or exposition is not relevant to the topic. |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------+
:::

In addition, I will consider:

::: column-page
+----------------------+--------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Consideration        | Moderate or Strong Evidence                                                                                  | Weak or No Evidence                                                                                                       |
+======================+==============================================================================================================+===========================================================================================================================+
| Accuracy             | The article accurately presents the data and its context, and any claims made are supported by the data.     | The article contains inaccuracies or does not sufficiently support any claims made (e.g. took the mean of a probability). |
+----------------------+--------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Context of Data      | The article provides context for the data, including the source, sample size, and any limitations or biases. | The article lacks context for the data or does not acknowledge any limitations or biases.                                 |
+----------------------+--------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Spelling and grammar | The article is well-written and free of major spelling and grammar errors.                                   | The article contains multiple spelling or grammar errors that distract from the content.                                  |
+----------------------+--------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Clarity of writing   | The article is clearly written and easy to understand, with a logical structure.                             | The article is confusing or difficult to follow, with unclear writing and a lack of structure.                            |
+----------------------+--------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Word count (250-500) | The article meets the word count requirement and covers the topic effectively within that range.             | The article is too short or too long, or does not sufficiently cover the topic within the word count range.               |
+----------------------+--------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
:::

## Acknowledgements

I would like to acknowledge [Amelia McNamara](https://www.amelia.mn/STAT336/OneNumberStory.html) for the original activity and [Brianna Heggeseth](https://bcheggeseth.github.io/) for modifications.
