---
title: "Writing about Data"
subtitle: "Stat 365: Statistical Communication"
format: 
  revealjs:
    theme: [default, ../slide_custom.scss]
    auto-stretch: false
editor: source
self-contained: true
execute:
  echo: true
---

## Monday, April 3rd

Today we will...

+ Introduction to the course
+ Writing about data
+ Review Syllabus
+ Tips for success

# Communicating about Data

##

### Data is a set of *variables* that capture various aspects of the world {style="text-align: center;"}

<br>

### It also contains *observations* over those variables {style="text-align: center;"}

## 

### Data can seem neutral, but it is always generated by humans {style="text-align: center;"}

## \#privlagealert

:::: columns
::: column
I am a

+ white
+ straight
+ cisgender
+ middle class
+ highly educated
+ American

lady
:::
::: column
I’m doing the best I can when I talk about issues of race, class, gender, and other sensitive topics. But you should *always* feel free to call me out (publicly or privately)
:::
::::

## Sometimes data is collected intentionally

+ The Census
+ Pew Research surveys
+ Science!
+ ...and of course, many more

## Sometimes data is collected for one reason and used for another

+ Health information about you at the doctor
+ Emails (think Enron trove!)
+ Location information from social media posts
+ ...and more!

## Brainstorm!

<br>

### Make a list of all the places you left “data exhaust” today/this week {style="text-align: center;"}

## Main communication types in this class

+ Writing about data (words)
+ Visualizing data (pictures) 

## Scientific writing

## Data journalism

## (and also, data viz!)

## Brainstorm!

<br>

### What other types of writing about data are there? {style="text-align: center;"}

<br>

### What distinctions can we draw inside the categories? {style="text-align: center;"}

# Syllabus

## Tips for success

+ Voice Dream
+ Keep track of important deadlines
+ Ask when clarification is needed
+ Be creative!

## To do

+ **Grade contract** (Canvas Quiz Submission)
  + Due Wednesday, 4/5 at 12pm
+ Read xxx
+ Review final technical report project outline & instructions (start brainstorming!)

