---
title: "Make your own website"
subtitle: "Grade Booster Activity"
format: 
  html:
    toc: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
editor: source
---

## Prompt:

GitHub is an incredibly useful tool for project management and collaboration. It also has several useful features for professional promotion: you can host your own site on github using [GitHub pages](https://pages.github.com/), describe yourself using a GitHub developer profile, and even use [resume.github.io](http://resume.github.io/) to generate a resume summary of your activity on GitHub (you must opt-in by [starring the project page](https://github.com/resume/resume.github.com)). 

posit and the associated package infrastructure provide multiple ways to generate websites using [Quarto](https://quarto.org/docs/websites/).

## Instructions:

1. Create a new GitHub repository named `<your-username>.github.io` (replacing "<your-username>" with your GitHub username). Initialize this repo with a readme.

2. Set up your website the Quarto instructions below. If you would like to use this repository to host a blog, you may find Quarto to be a more convenient option.

3. Link to your new website!^[You will submit this to Canvas.]

To satisfy, you should modify your site beyond the default template files, adding at least some content that is unique to you - packages you find interesting, sites you enjoy, projects you have worked on, a page with your resume, etc.
 
### Quarto Website

1. Install/Update the `quarto` package (`install.packages("quarto")`)

2. Create a new folder where you will store your blog and the rendered site.

3. Use RStudio to create a new project inside the folder you created in step 2. Select either the Option "Quarto Website" or "Quarto Blog" as the project type.

4. Follow the Quick Start instructions on <https://quarto.org/docs/websites/website-blog.html> to create your website (or a generic site at <https://quarto.org/docs/websites/>).

5. For publishing your website, follow the steps described under [Github Pages](https://quarto.org/docs/publishing/github-pages.html). You can try to build the site automatically, but fair warning: I went back to build to docs and render the site myself. 
  + VERY IMPORTANT: add `output-dir: docs` to your YAML file.

6. VERY IMPORTANT. Open the "username.github.io" project. Add a text file named ".nojekyll" (the file should be empty). This tells GitHub not to build the pages with Jekyll (another rendering engine) and instead render pages built with Quarto.

See an additional resource at this [blog post](https://ucsb-meds.github.io/creating-quarto-websites/)
:::

## Rubric posted to Canvas.
