---
title: "NYT What's going on in this graph?"
subtitle: "Grade Booster Activity"
format: 
  html:
    toc: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
editor: source
---

<!-- ::: callout-warning -->
<!-- As of May 5th, we will be using our discord server to conduct a "Pseudo, NYT What's Going on in This Graph" due to the end of the NYT activity for this academic year. See Canvas for the link to join. -->
<!-- ::: -->

## Prompt

Together, the [American Statistical Association](https://www.amstat.org/whats-going-on-in-this-graph) and the [New York Times](https://www.nytimes.com/column/whats-going-on-in-this-graph), put out a weekly graph related to current times.

Each Thursday afternoon, the New York Times Learning Network publishes a new What’s Going On in This Graph?

The following Wednesday, Statistics teachers provide live moderation of student comments from 6 a.m. to 11 a.m. PT. ^[I encourage you to contribute to the discussion once in a while, but you are not required to join the live moderation.]

## Instructions

In order to meet the conditions of the contract for this activity, you must:

+ Visit <https://www.nytimes.com/column/whats-going-on-in-this-graph> weekly for the selected chart.

+ Write a reflection that addresses the following questions:
  + What do you notice?
  + What do you wonder?
  + What impact does this have on you and your community?
  + What is a catchy headline that captures “what’s going on this graph”?

::: callout-tip
Your reflection should be well formulated and written. Let your creativity show!
:::

+ Miss no more than 2 weeks throughout the quarter.

+ Join the conversation and submit your reflection to the NYT by clicking on the comment button and posting in the box. ^[Email me for an alternative option if you have FERPA and do not wish to put information online.]
  + Below the response box, there is an option to click on “Email me when my comment is published.” This sends the link to your response which you will submit weekly to Canvas by Tuesdays at 11:59pm ^[I will do my best to provide timely feedback to your submissions.].
  
+ After you have posted, read what others have said, then respond to someone else by posting a comment. Use the “Reply” button to address that student directly.

On Friday mornings, the NYT will reveal more information about the graph, including a free link to the article that includes this graph, at the bottom of this post. I encourage you to post additional comments based on the article, possibly using statistical terms defined in the [Stat Nuggets](https://docs.google.com/document/d/1X9ECSnq1T12Fw402vmo4Lgz3w-cXNSJw/edit).

