---
title: "The Stats+Stories 300th Episode Data Visualization Contest "
subtitle: "Grade Booster Activity"
format: 
  html:
    toc: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
editor: source
---

## Prompt

In a recent podcast episode of Stats+Stories, they put out a call for you to participate in their our 300th episode.

Listen to the podcast episode at <https://statsandstories.net/contest>

They have put out a [data set](https://docs.google.com/spreadsheets/d/1Hsktt16o18TcxcMOMZnqYhckcgsFa5otwU932l6BUpw/edit?usp=sharing) containing various information on over 280 episodes of Stats+Stories recorded over the past decade, which they want you to use to create visualizations and tell a story with their data!


## Instructions

To satisfy the conditions for this challenge, you should:

+ Access the data -- You can view the full document (via [Google Docs](https://docs.google.com/spreadsheets/d/1Hsktt16o18TcxcMOMZnqYhckcgsFa5otwU932l6BUpw/edit?usp=sharing)), as well as download the data as an [Excel](https://statsandstories.net/s/StatsStories-300th-Episode-Data-Visualization-Contest.xlsx) file or view the [Key](https://statsandstories.net/s/StatsStories-300th-Episode-Data-Visualization-Contest-Key.csv) and [Data](https://statsandstories.net/s/StatsStories-300th-Episode-Data-Visualization-Contest-Stats.csv) as separate CSV files.

+ Use either RShiny or Tableau to create a dynamic dashboard and tell a story with the data.

+ Submit your entry by filling out the form on the contest page.^[All entries must be submitted by June 29th at 9:00 PM PST. The finalist will be selected and announced the day after and fan voting will take place until August 31st at 8:59 PM PST. The winner will be featured on the 300th episode of Stats+Stories and will receive a copy of John and Rosemary's new book "Statistics Behind the Headlines", as well as some Stats+Stories swag.]

+ Submit your entry to Canvas.
