---
title: "Data Descriptions"
subtitle: "Stat 365: Statistical Communication"
format: 
  pdf:
    self-contained: true
editor: source
---

# Critique my Mandela data description!

I conducted a study to determine the effect of numerical anchoring bias. In my Spring 2023 Statistical Communication class, I asked all students in attendance on the day of data collection to voluntarily make a guess about Mandela's age after being provided a prompt. The sampling method for anchoring bias was a convenience sample, limiting my scope of inference to Cal Poly statistics student's currently enrolled in my course. Student's absent the day of data collection were not included in the study.

To collect the data, I randomly provided each student a paper including one of the two following survey numerical anchoring prompts and question:

+----------+-------------------------------------------------------------------------------+
| Prompt 1 | Was Nelson Mandela, the first president of South Africa following apartheid,  |
|          |                                                                               |
|          | older or younger than age **120** when he died?                               |
+----------+-------------------------------------------------------------------------------+
| Prompt 2 | Was Nelson Mandela, the first president of South Africa following apartheid,  |
|          |                                                                               |
|          | older or younger than age **12** when he died?                                |
+----------+-------------------------------------------------------------------------------+
| Question | Make a guess for Mandela's age (in years) when he died.                       |
+----------+-------------------------------------------------------------------------------+

During class, students filled out the survey questions and later submitted their answers to a Canvas quiz for data collection. The data set contains information about the prompt, indicating if the student was numerically anchored to a large age of 120 years or a younger age of 12 years as well as the student's guess for the age at which they believed Mandela died. A total of 47 students participated in the study and I did not measure covariates for each participant.

\vspace{2.5cm}

# Let ChatGPT try!

I asked ChatGPT to provide me three versions which describe the variables from a data set which recorded information about kangaroo behaviors.

-   Read each description and make a list of its pros and cons.
-   What information is missing?
-   How might you improve upon these descriptions?

### Prompt

A study ([Brunton et al. 2019](https://www.mdpi.com/2504-446X/3/2/41)) recorded the response of kangaroos to drones (one of 'Vigilance', 'No vigilance', 'Flee \<10 m', or 'Flee \>10 m') and the altitude of the drone (30m, 60m, 100m or 120m). The mob size and sex of the kangaroo was also recorded. Describe the variables in the study.

### Version 1

In the study conducted by Brunton et al. in 2019, the researchers recorded several variables related to kangaroo behavior in response to drones. These variables included the response of kangaroos to drones, which was categorized into four types ('Vigilance', 'No vigilance', 'Flee \<10 m', or 'Flee 10 m'), as well as the altitude of the drone (30m, 60m, 100m, or 120m). The researchers also recorded the size of the kangaroo mob and the sex of the kangaroos.

\vspace{2.5cm}

\newpage

### Version 2

-   **Response of Kangaroos to Drones:** This variable refers to the response categories of the kangaroos to drones, which were classified into four categories; 'Vigilance', 'No vigilance', 'Flee \<10 m', and 'Flee \>10 m'. This variable was measured on a categorical scale.

-   **Altitude of the Drone:** This variable refers to the height at which the drone was flown during the study, which was measured in meters. The altitude was measured on a continuous scale.

-   **Mob Size:** This variable refers to the number of kangaroos in a group or mob, which was recorded during the study. Mob size was measured on a discrete scale.

-   **Sex of Kangaroo:** This variable refers to the sex of the kangaroo, which was recorded as either male or female. This variable was measured on a nominal scale.

\vspace{2.5cm}

### Version 3

In a study conducted by Brunton et al. in 2019, four variables were used to investigate the response of kangaroos to drones. These variables include the response of kangaroos to drones, altitude of the drone, mob size, and sex of the kangaroo. The response of kangaroos to drones was recorded as one of four categories: 'Vigilance', 'No vigilance', 'Flee \<10 m', and 'Flee \>10 m'. Altitude of the drone was recorded in meters on a continuous scale, while mob size was recorded as the number of kangaroos in a group or mob, and was measured on a discrete scale. Lastly, sex of kangaroo was recorded as either male or female and was measured on a nominal scale.

\vspace{2.5cm}

### Write your own kanagroo drone variable description.

\vspace{5cm}

# Use active voice! (by zombies) test for passive voice!

-   Read each statement and determine if it is active or passive voice.
-   If the statement is passive voice, fix the statement to be written in active voice.

**Passive:** The form was processed and returned (by zombies).

**Active:** We completed your request and mailed the form to you.

\vspace{1.5cm}

Twenty-seven shots were taken from the three point line.

\vspace{1.5cm}

Researchers had their questions answered in a special session with Bill Nye the Science Guy.

\vspace{1.5cm}

I recruited 43 full-time Cal Poly students to participate in my study.
