---
title: "Technical Report Project"
subtitle: "Stat 365: Statistical Communciation"
format: 
  html:
    toc: true
    number-sections: true
    number-offset: 1
    self-contained: true
    theme:
      light: flatly
      dark: darkly
editor: source
---

::: callout-note
You can choose to use whichever document editors (Word, google docs, RMarkdown, Quarto) and statistical software programs (R, SAS, Python, JMP, Minitab) you are most comfortable using as long as they can appropriately carry out your analysis. However, you must submit all check-point draft documents and your final report as .pdf file extensions so I can provide written feedback within Canvas via my iPad.

If you have the background and skills, I do encourage you to use a scripting language (R, SAS, Python), etc. and good graphical tools (ggplot2, Tableau, Datawrapper).

There are packages in R that provide templates for scientific articles that you might want to look into: `rticles`, `papaja`, `distill`. However, I think these might be Rmarkdown based and not Quarto based.
:::

# Important Dates {.unnumbered}

*Due dates may be subject to change, but only to your benefit*

+----------------------------------------------+-------------------------------+
| Component                                    | Due Date                      |
+==============================================+===============================+
| Initial Proposal                             | Monday, April 10 at 12pm      |
+----------------------------------------------+-------------------------------+
| Formal Protocol                              | Thursday, April 13 at 11:59pm |
+----------------------------------------------+-------------------------------+
| Peer Review of Formal Protocol               | Tuesday, April 18 at 11:59pm  |
+----------------------------------------------+-------------------------------+
| Data Collection                              | Monday, April 24 at 12pm      |
+----------------------------------------------+-------------------------------+
| Draft: Data and Methods + Table              | Monday, May 1 at 12pm         |
+----------------------------------------------+-------------------------------+
| Draft: Results and Discussion + Graphic      | Monday, May 15 at 12pm        |
+----------------------------------------------+-------------------------------+
| Draft Submission + Introduction & Conclusion | Monday, May 29 at 12pm        |
+----------------------------------------------+-------------------------------+
| Final Submission                             | Wednesday, June 14 at 5pm     |
+----------------------------------------------+-------------------------------+

# Reproducibe Workflow {.unnumbered}

As a part of this project, you will demonstrate reproducible workflows and research. Following the guidelines in [Third Time's a Charm: A Tripartite Approach for Teaching Project Organization to Students](https://amstat.tandfonline.com/doi/epdf/10.1080/26939169.2022.2118644?needAccess=true&role=button), your root project folder should include:

-   `README.txt` file to orient someone to the electronic files or for processes that will be repeated throughout a study (e.g., specific data cleaning rules and scoring algorithm at multiple time points). Ideally the root project folder will be stored on a secure server and/or cloud location (such as Git repository or OneDrive) that meets all project regulatory needs with access limited to approved team members while allowing for version control.

and the following sub-folders

-   `data` stores all data sets associated with the project (including original, analytic data sets, format files, etc.). The data folder should have a sub-folder where an original, raw, uneditable version of the data is archived and used for import into statistical software (similar to data and data_raw approach in R packages, Wickham, Bryan, and Barrett2022). Projects with many different data sources can have a separate sub-folder for each source

-   `documents` stores all of the written documents for the project. There may be sub-folders for references (statistical and/or domain), article or conference submissions, primary literature/scoring manuals for psychometric scales and other constructs, etc. Importantly, you must document decisions and revised analytic plans during the course of the project.

-   `results` stores all output from the scripts and any derived tables and figures. Spreadsheets, Word tables, RTF files, plots, figures, PDFs of output, all are stored in this folder. If statistical scripts directly produced it or it was created from results derived from statistical scripts, the files should go in this folder.

-   `scripts` stores all statistical programs/syntax/scripts/code (called "scripts" hereafter) used for the project (and statistical scripts should be used as much as possible when handling data!). Much of the documentation of our work is included in statistical scripts tailored to each individual project. Script file names should explicitly describe what step in the research process the script is for and what the script is intended to do, from reading in the original data to creating the analytic data set to summary statistics to multi-variable modeling. RMarkdownfiles / Quarto files (except for your technical report document(s) if using this document editor for your formal writing) should be stored here as well (Baumeret al 2014; Dvoraketal 2019; Allaireetal 2022).

-   Always use good programming practice, which includes: informative script headers, readable code, use of comments,and creation of separate scripts for distinct parts of the project. See CwD ch. 8 about documenting your code.

-   If you are using a non-scripted language (JMP, Minitab, etc.) please make sure to include a document which describes the steps you took in analyzing the data.

In your final submission, you will turn in a .zip file of your project folder in order for me to evaluate your organization and workflow.

# Study Proposal {.unnumbered}

For your technical report assignment, you will be required to propose a research project that can be easily executed within 1-2 days. Your project should be:

-   an experiment with
-   a quantitative response variable (other ideas for response variables are also welcome),
-   and a categorical explanatory variable that compares two or more groups.

You should aim to collect approximately 50 observations.

To ensure you have a well-developed proposal, review [Cal Poly's Guidelines for Protocol Development](https://research.calpoly.edu/HS-guidelines#_Guidelines_for_Protocol) and this [article](https://www.aje.com/arc/how-to-write-an-easily-reproducible-protocol/) on how to write an easily reproducible protocol.

::: callout-note
Some parts (e.g., Human subjects) may be less relevant to you and that's fine! I would focus less on criteria for approval, and more on providing enough details that someone else could carry out the study you have designed (4(a), (c), (d)).
:::

::: {.callout-tip collapse=true}
## Considerations for the research protocol
+ Put the methodology in context
  + Research question and objectives
+ Research Design
  + The choice of the design should be explained in relation to the
study objectives (treatments, response, observations, etc.)
+ Materials and tools
  + If you will be using subjects/participants, the following questions should be answered:
    – What are the criteria for inclusion or selection?
    – What are the criteria for exclusion? 
+ A chronology of steps
  + Think like a detailed recipe.
  + Provide information and justification about sample
size.
+ Notes, recipes, tips, and tricks
:::

**Deliverables**:

-   Submit a brief **initial proposal** (research question, explanatory and response variables, and a very brief explanation of the data collection process -- sample size, materials, etc.) for feedback from myself by **Monday, 4/12 at 12pm**
-   and a **formal study protocol** (as if to a Human Subjects Review board) by **Thursday, 4/15 at 11:59pm**.

Your formal study protocol will be peer-reviewed by a fellow student who will conduct a pilot study, gathering about 5 observations.

::: callout-note
Any written document you submit to me should be well written (grammar, spelling, complete sentences, etc.).
:::

### Peer review formal study protocol {.unnumbered}

For the technical report project, the peer review process will begin on **Friday, 4/14 at 8am**. You will be able to access the assigned protocol by clicking on a link under *"Assigned Peer Reviews"* on the right-hand side of the assignment. You will then fill out a rubric (*"Show Rubric"*) and add comments to provide constructive feedback to your peer.

+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+
| Criteria                                                                                              | Evidence | Weak Evidence | No Evidence |
+=======================================================================================================+==========+===============+=============+
| **Details**                                                                                           |          |               |             |
|                                                                                                       |          |               |             |
| How well did the protocol answer questions you had about collecting the data?                         |          |               |             |
+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+
| **Instructions**                                                                                      |          |               |             |
|                                                                                                       |          |               |             |
| Were the instructions concise and easy to follow?                                                     |          |               |             |
+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+
| **Context**                                                                                           |          |               |             |
|                                                                                                       |          |               |             |
| Did the protocol start with a description of the "context"/why the data were being collected?         |          |               |             |
+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+
| **Definitions**                                                                                       |          |               |             |
|                                                                                                       |          |               |             |
| Were all necessary definitions and descriptions (e.g., of equipment) clearly provided?                |          |               |             |
+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+
| **Step-by-step**                                                                                      |          |               |             |
|                                                                                                       |          |               |             |
| Were step-by-step instructions provided?                                                              |          |               |             |
+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+
| **Other advice**                                                                                      |          |               |             |
|                                                                                                       |          |               |             |
| Please describe any other questions or advice you have for the project before data collection begins! |          |               |             |
+-------------------------------------------------------------------------------------------------------+----------+---------------+-------------+

Please email me right away if you have any problems with this process.

# Data Collection {.unnumbered}

Collecting high-quality data is crucial for the success of your technical report project. After receiving peer-reviewed feedback, you should conduct your study and collect data meeting the specified sample size and following the protocol outlined in your study proposal. Keep in mind any suggestions or comments from the peer review process.

Store your data in a tidy format in a `.csv` or `.xlsx` file, and save it within your `data` folder as your original data file in accordance with reproducibility guidelines.

# Final Technical Report {.unnumbered}

The final technical report is the ultimate goal of your research project. In this assignment, you will produce a scientific journal-style article, which will demonstrate your research findings and conclusions. You will be supported with guidelines and resources to facilitate the writing process. Throughout the quarter, you will receive feedback and guidance to ensure that you produce a high-quality report.

I have outlined the different sections and components that are expected in the final technical report below.

## Abstract / Executive Summary

::: callout-warning
While the abstract is the first thing a reader sees, this will be the last piece we write.
:::

The Abstract/Executive Summary is a brief, non-technical summary of your research project, and should be around 150-250 words in length. Its purpose is to provide an overview of your project and its significance to the reader.

To create a compelling and accurate abstract, you should consider the following guidelines:

-   Write a stand-alone summary of the project that can be understood without reading the full report.
-   Be clear and concise, avoiding technical language and jargon.
-   Discuss the project's objectives, purpose, background, and why it is important.
-   Describe the data and methods used in the project, including who, what, when, where, how, and the sample size.
-   Highlight the key findings and results of the project.
-   Conclude with recommendations or conclusions that relate to the project's objectives.
-   Avoid introducing any new information that is not discussed in the main report.

## Introduction

The introduction section is where you will hook your reader and draw them into your research project.

This section should:

-   Begin with an attention-grabbing opening statement to engage the reader.
-   Provide background information on the topic and describe any existing theories, research or literature that are relevant to the study.
-   State the research question and explain how the study aims to answer it.
-   Highlight the significance of the study by identifying the potential benefits and contributions to the field
-   Provide an overview of the structure of the report, outlining the major sections and their content (tell the reader what you are going to tell them).

## Data and Methods

In the Data and Methods section of your technical report, you will describe the design of your study and the methods used to collect and analyze the data.

Here are some key components to include:

-   A concise overview of your research question and hypothesis
-   Details on the sample size and selection process, including any inclusion/exclusion criteria
-   A description of the data collection methods used, including measurement tools and techniques
-   A description of the variables used and their definitions.
-   An explanation of any data manipulations made before analysis, including any constructed variables.
-   An explanation of how the data were analyzed, including any statistical tests used to determine significance
-   A discussion of any potential flaws or limitations in the study design, including any data that was excluded or removed
-   (Optional) The use of tables or diagrams to help illustrate your experimental design.

Remember to keep supporting or background data not critical to the flow of the main report in appendices and to reference data from other sources so readers can locate it.

::: {.callout-tip collapse="true"}
### Tip: Remember to focus on the When, Where, How, Who, What:

-   When and where did the study take place?
    -   Was there randomness or more of a convenience sample?
-   Who are the subjects under study? ("subjects" don't have to be people)
    -   Any inclusion/exclusion criteria?
-   What procedures were used to select subjects and collect measurements?
-   Exactly how were the outcomes measured, describe any measurement devices, units of measure
-   Describe the treatments
    -   Include copies of any surveys/questions
    -   Include photographic evidence?
-   Describe the randomization
-   What are the outcomes and covariates?
-   What are the potential flaws/limitations?
-   Were any observations removed? (If so, why?)
:::

::: callout-note
Remember to be thorough yet concise!
:::

### Table of Summary Statistics {.unnumbered}

Your Data and Methods section should include a descriptive statistics table to summarize your data. For quantitative response variables, this will typically involve comparing means, medians, and other summary statistics such as standard deviations and five number summaries. For categorical response variables, you will compare proportions, being cautious to interpret proportions and percentages appropriately, especially differences. To do this effectively, I recommend creating a table that presents your results in a clear and concise format.

Here are some key considerations to keep in mind:

-   Use headings and captions to clearly label the table and help the reader understand the content.
-   Keep the table simple and easy to read, avoiding unnecessary detail or clutter.
-   Be sure to provide appropriate units of measure and any relevant notes or explanations.
-   Consider highlighting key results or differences to draw the reader's attention.

Review the lecture slides and podcasts from the *Chicago Guide to Writing About Numbers* (Chapters 6 and 7) for additional guidance and *Show Me the Numbers* by Stephen Few as a supplemental resource

## Results and Discussion

The Results and Discussion section of your technical report is where you will present your findings and explain what they mean in the context of your research question and hypothesis. Keep in mind that you should assume a reasonably educated audience, but avoid technical jargon and use formal language in the active voice ("by Zombies" test). This section should engage the reader's interest and be succinct, so it's important to focus on the flow and readability of your report.

While separating the results and discussion sections is a common practice, you can choose to integrate them together. It's also possible to separate the exploration data analysis from the inferential analysis, but make sure not to be too repetitive. In this section, you should provide a clear and concise overview of your findings and explain their significance in the context of the research question. Make sure to refer back to your hypothesis and discuss whether your findings support or refute it. Finally, be sure to highlight any limitations or potential sources of error in your study.

### Results

The results section is where you present your findings and interpretation of the data you have collected. This section should be well-organized and easy to follow, with clear graphs and tables that effectively illustrate your analysis.

Here are some key components of the results section:

-   Begin with an introduction that provides some context to your output. Then, provide an analysis of your data and mention which package(s) you used. Avoid including every data analysis result, but be sure to make all methods clear.
-   Include high-quality graphs and tables to effectively summarize your results.
-   Interpret your findings using GEE or ADEPT strategies. Summarize your results both technically and in a way that a non-statistician can understand.
-   Discuss what you observe and summarize your findings, including any overall patterns and any exceptions, as well as the strengths and limitations of your data collection and analysis methods.
-   Provide a graph and summary statistics of your response variable across groups. Use a histogram or dot plot for quantitative data (means and SDs), and a bar graph for categorical data (conditional proportions of successes). Create effective, high-quality visuals with value ordering, color use, and correct units of measurement (not too many significant digits).
-   Test for statistical significance by comparing your groups and provide confidence intervals. Ensure that your analysis matches your graphs (e.g., compared two groups on a quantitative response, look at a two-sample t-test). Avoid shocking the reader with surprising analysis results based on what you pointed out in the graphs.

Summarize your statistical significance and the size of the "effect," focusing mainly on the facts. The discussion section will have more interpretation.

### Discussion

The discussion section is where you interpret your findings and summarize what you learned from the analysis about your overall research question. In this section, you can also discuss the strengths and limitations of your study and provide directions for future research.

Here are the key components of the discussion section:

-   Interpret your findings and summarize what you learned from the analysis about your overall research question.
    -   Did the data behave as you expected?
    -   Is the result statistically significant? How large is the effect? Would you consider it practically significant? How are you deciding? (Do you need to bring in any subject-matter knowledge here?)
    -   Use examples or analogies to help clarify your points and make your discussion more accessible to a broader audience.
-   Strengths (don't restate but interpret) of data collection and analysis methods
    -   Can you draw cause-and-effect conclusions?
    -   To what population are you willing to generalize?
    -   How does your study contribute to the existing knowledge base and the larger context?
-   Critically assess any limitations or potential biases and how they impacted the interpretation of your findings.
    -   Note any deficiencies or unexplained data.
    -   Any issues with the analysis methods used?
    -   Any other potential sources of error or biases?
-   Suggest directions for future research and identify areas that require further investigation.

## Conclusion

The conclusion section is the final chance to leave a lasting impression on your readers and drive home the significance of your research. Here are some tips for crafting a strong conclusion:

-   Recap the main points of your study, including any important findings or trends (tell them what you told them)
-   Discuss the scope of your conclusions, and **justify your reasoning**. Can you generalize your results to a larger population? Can you infer causality? Explain why or why not.
-   Consider the practical significance of your results, and explain how you are measuring this. Are the results meaningful in a real-world context?
-   Return to the big picture, and address the research question. Have you answered it? Can you make any recommendations based on your findings?
-   Finally, offer suggestions for future research that could build on your study and address any lingering questions or uncertainties.

## References

The reference section is an essential part of your academic work and should be included following APA citation style. It should contain a list of all the sources you have used, including textbooks, research papers, and statistical software or packages. By including a reference section, you provide your readers with the opportunity to access and verify the information you have used.

## Appendix

An appendix is a supplementary section that provides additional information to support your research.

Your appendix should include:

-   The appendix may include the original research protocol.
-   Additional relevant documentation that provides further insight into your research methodology and analysis.
-   A raw data file, which contains the original data collected during your research.

# Final Submission {.unnumbered}

Your submission should include

1.  A version of your report showing track changes in individual pieces
2.  A brief discussion of changes made to original pieces of report along the way
3.  Final report (see draft rubric below)
4.  The .zip folder of your project folder demonstrating your reproducible workflow

**Formatting:** Your final report should use

-   12 point font
-   1 inch margins
-   Reasonable font choice
-   Double spaced pdf file
-   If you have references, use APA citations

**Contents:** Your final report should have the sections and related contents as described above.

**Revisions:** You should also be submitting your discussion of the changes you made and any annotated previous versions as separate files.

# Editing Checklist {.unnumbered}

-   Title page lists the title, authors, date.
-   Present, active voice ("by Zombies" test); professional tone; no personal opinions
-   Concise (vs. use of unnecessary words)
-   Gender-neutral wording
-   Acronyms and Abbreviations defined the first time used
-   Subject/verb agreement
-   Correct spelling (don't rely only on spell checker)
-   Correct use of punctuation and grammar
-   Figures and Tables numbered and in correct location (include captions, figure alt. text, and in text references to these additional aids).
-   Supporting documentation in appendices
-   Figures, tables, and appendices referred to accurately.
-   Bulleted and numbered lists have parallel construction and consistent punctuation.
-   Use brief, descriptive (left-justified, bold, title capitalization) headings to help readers navigate easily through the document. Heading levels follow sequentially. If you create one subhead, you must have at least two. For example, don't create heading 1.1.1 without a heading 1.1.2. If information for only one subhead exists, it should all appear under the main heading, 1.1.
-   Follows basic rules for
    -   Commas
    -   Colons
    -   Semicolons
    -   Hyphens
    -   Acronyms
    -   Numbers (writing the word vs. the numeral)
    -   Equations (using symbols)
    -   Units of measure

# Final Report Rubric {.unnumbered}

To meet the requirements for the contract, this project must:

-   be turned in on time,

-   include all components described above

-   Meet quality guidelines laid out in the following rubric. In order to meet "satisfactory" for your contracted grade:

    -   A must receive all 3's (or above) on the main components, and demonstration of all additional writing/project components

    -   A- must receive all 3s (or above) on the main components with at most one 2, and demonstration of all additional writing/project components.

    -   B+ must receive all 3s (or above) on the main components with at most three 2s, and demonstration of all additional writing/project components.

    -   B must receive all 2s (or above), and demonstration of all additional writing/project components.

    -   B- must receive all 2s (or above) with a most one 1, and demonstration of all additional writing/project components.

    -   C+ must receive all 2s (or above) with a most three 1s, and missing demonstration for at most 4 additional writing/project components.

    -   C must receive all 1s (or above), and missing demonstration for at most 4 additional writing/project components.

    -   C- must receive all 1s (or above) with at most one 0, and missing demonstration for at most 4 additional writing/project components.

    -   D+ is the *maximum* grade you might obtain from no final submission. In this case grade evaluation will be determined by your previously submitted drafts and other course work.

This means that if you are aiming for an A, complete three booster activities, miss no more than 3 assignments, meet "satisfactory" on your mini-projects, but receive all 2s on your final technical report, you will get a B in the course. Similarly, if you complete one booster activity, miss no more than 3 assignments, meet "satisfactory" on your mini-projects, and receive all 3's on your final technical report, you will get a B+ in the course.

Any deviation to these guidelines will be to your benefit.

<br>

*The table below outlines the main components of your technical report:*

::: column-page
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
| Main Component                                                                            | 4 - above and beyond evidence | 3 - strong evidence             | 2 - moderate evidence | 1 - weak evidence | 0 - no evidence |
|                                                                                           |                               |                                 |                       |                   |                 |
|                                                                                           |                               | (a 3 is considered full credit) |                       |                   |                 |
+===========================================================================================+===============================+=================================+=======================+===================+=================+
| **Abstract/Executive summary *(\~120 words, limit 250 words)***                           |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Plain language, Overview, Engaging                                                        |                               |                                 |                       |                   |                 |
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
| **Introduction**                                                                          |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Clarify objectives, but not too much detail                                               |                               |                                 |                       |                   |                 |
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
| **Data and Methods**                                                                      |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Ws                                                                                        |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Study design details                                                                      |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Study design issues (e.g., missing data)                                                  |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Analytic sample, representativeness                                                       |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Variables/Units/Getting to know your data                                                 |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Outliers                                                                                  |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Name of statistical methods                                                               |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Critique of statistical methods/validity                                                  |                               |                                 |                       |                   |                 |
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
| **Results**                                                                               |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Include graphical summaries of your data and statistical analyses                         |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Quality/Effectiveness of visuals/tables                                                   |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| e.g., units of measurement, not too many significant digits, value ordering, use of color |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Titles/Axis labels/Annotations/Legends/Captions/Alt Text/Scaling                          |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Figures in line with text                                                                 |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Introductory sentences of tables, charts, comparisons                                     |                               |                                 |                       |                   |                 |
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
| **Discussion**                                                                            |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Summaries of major findings                                                               |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Effective comparisons                                                                     |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Direction, magnitude, significance                                                        |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Generalizations, Examples, and Exceptions                                                 |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Interpretation of numeric evidence                                                        |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Connections to research questions                                                         |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Reflection on strengths, limitations                                                      |                               |                                 |                       |                   |                 |
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
| **Conclusion**                                                                            |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Scope of conclusions                                                                      |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Substantive significance                                                                  |                               |                                 |                       |                   |                 |
|                                                                                           |                               |                                 |                       |                   |                 |
| Recommend appropriate action?/Directions for future research                              |                               |                                 |                       |                   |                 |
+-------------------------------------------------------------------------------------------+-------------------------------+---------------------------------+-----------------------+-------------------+-----------------+
:::

<br>

*In addition to the main components of the technical report, you must demonstrate competency (moderate or strong evidence) of the following written and project parts:*

::: column-page
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| Writting/Project Component                                            | Moderate or Strong Evidence | Weak or no Evidence |
+=======================================================================+=============================+=====================+
| **Reproducibility**                                                   |                             |                     |
|                                                                       |                             |                     |
| .zip folder containing: README, data, documents, results, and scripts |                             |                     |
|                                                                       |                             |                     |
| Good programming practices and code/analysis documentation            |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Revisions**                                                         |                             |                     |
|                                                                       |                             |                     |
| Copy or original drafts with track changes                            |                             |                     |
|                                                                       |                             |                     |
| Discussion of edits made along the way                                |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Title page**                                                        |                             |                     |
|                                                                       |                             |                     |
| Title, Author, Course, Date                                           |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Overall Clarity**                                                   |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Appearance**                                                        |                             |                     |
|                                                                       |                             |                     |
| e.g. section headings, page breaks, details, figure/table numbers     |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Overall cohesion/flow of story**                                    |                             |                     |
|                                                                       |                             |                     |
| e.g., Transition sentences                                            |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Grammar/Spelling/Appropriateness of vocabulary/Punctuation**        |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
| **Correct use of statistical language**                               |                             |                     |
+-----------------------------------------------------------------------+-----------------------------+---------------------+
:::
