---
title: "Make your own website"
subtitle: "Grade Booster Activity"
format: 
  html:
    toc: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
editor: source
---

## Prompt:

GitHub is an incredibly useful tool for project management and collaboration. It also has several useful features for professional promotion: you can host your own site on github using [GitHub pages](https://pages.github.com/), describe yourself using a GitHub developer profile, and even use [resume.github.io](http://resume.github.io/) to generate a resume summary of your activity on GitHub (you must opt-in by [starring the project page](https://github.com/resume/resume.github.com)). 

posit and the associated package infrastructure provide multiple ways to generate websites using Quarto (or Rmarkdown). You can satisify the conditions for this grade booster activity using one of two options: 

- Simple RMarkdown websites    
For more information about simple R Markdown websites, please read the documentation at <https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html>. Simple R Markdown sites are _not_ based on **blogdown**. They are probably good for websites with only a few Rmd documents.

- [Quarto](https://quarto.org/docs/websites/)^[I recommend using Quarto.]    
For larger-scale and more sophisticated websites (such as blogs), you may want to use **Quarto** instead: https://quarto.org/docs/websites/.

- Alternatively, you could look into the R package [portfoliodown](https://medium.com/nerd-for-tech/cabuilding-a-data-science-portfolio-website-in-15-minutes-84f93501bad8) ([see example](https://mattdancho.netlify.app/)) if you want something that appears to be more buisness/industry focused. However, I think the Quarto option has some good frameworks for this now!.^[Disclaimer I have not used this package as I created my personal website a few years ago using Blogdown -- creation of Quarto and integration with GitHub have changed a lot since then!]

## Instructions:

1. Create a new GitHub repository named `<your-username>.github.io` (replacing "<your-username>" with your GitHub username). Initialize this repo with a readme.

2. Set up your website using either the Simple Markdown Site or the Quarto instructions below. If you would like to use this repository to host a blog, you may find Quarto to be a more convenient option, however, it is (just a bit) more complicated than the simple Rmarkdown site. 

3. Write about you experience -- and link to your new website!^[You will submit this to Canvas.]

To satisfy, you should modify your site beyond the default template files, adding at least some content that is unique to you - packages you find interesting, sites you enjoy, projects you have worked on, a page with your resume, etc.

::: {.callout-note collapse=true}
### Simple RMarkdown Site

1. Use RStudio and set up a new project on your machine linked to the GitHub repository you just created. 

2. Create two files in your project folder:
    - `_site.yml`:
      ```
      name: "my-website"
      output_dir: "."
      navbar:
        title: "My Website"
        left:
          - text: "Home"
            href: index.html
      ```
    
    - `index.Rmd`
      ```
      ---
      title: "My Website"
      ---
      
      Hello, Website!
      ```

3. Use the commmand `rmarkdown::render_site()` to build your website (Or click the "Build Website" button under the Build tab in RStudio). This command will compile any R markdown document in the main project directory to HTML (even if it is not mentioned in `_site.yml`). 

4. Push your site to GitHub. In this instance, you want to include the HTML files that were rendered, the `site_libs` directory, the `_site.yml` file used to configure the build process, and the Rmd files used to render the HTML files.

5. Customize your site. Remember to use the command `rmarkdown::render_site()` before you push your changes so that the HTML is updated!
    - Modify `_site.yml` to update the header structure, add links to other files, etc. 
    - Modify `index.Rmd` to add content to the landing page of your site. You might think about including a link to your CV on this page. 
    - Add new Rmd files to add new pages to your site. Consider adding a page describing your favorite packages, or pages for different projects you've worked on. 
:::    
   
::: {.callout-note collapse=true} 
### Quarto

1. Install/Update the `quarto` package (`install.packages("quarto")`)

2. Create a new folder where you will store your blog and the rendered site.

3. Use RStudio to create a new project inside the folder you created in step 2. Select either the Option "Quarto Website" or "Quarto Blog" as the project type.

4. Follow the Quick Start instructions on https://quarto.org/docs/websites/ or https://quarto.org/docs/websites/website-blog.html to create your website.

5. For publishing your website, follow the steps described under [Github Pages](https://quarto.org/docs/publishing/github-pages.html). You can try to build the site automatically, but fair warning: I went back to build to docs and render the site myself. 
  + VERY IMPORTANT: add `output-dir: docs` to your YAML file.

6. VERY IMPORTANT. Open the "username.github.io" project. Add a text file named ".nojekyll" (the file should be empty). This tells GitHub not to build the pages with Jekyll (another rendering engine) and instead render pages built with Quarto.

See an additional resource at this [blog post](https://ucsb-meds.github.io/creating-quarto-websites/)
:::
